server:
  port: 7001
#mybatis:
#  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
#  type-aliases-package: com.kennie.entities    # 所有Entity别名类所在包
#  mapper-locations:
#    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
#spring:
#  application:
#    name: sc-dept8001
eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/ #http://${eureka.instance.hostname}:${server.port}/eureka/